sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product testn-048
env:
  global:
    -
      # LTD_AWS_ID
      secure: JpxQjfmhjfUX6jtARyX/IVkU987Dz2I1Zuutmm7TZGPwp1teH8tzvlElKC0536SWbQFxpIIVbnUlEbLnPRcnINK2atfV6tNZ7qPOvpn+GwqfhLZ/LFRG5labfKeGNp9IXp+us8sq26+GM1xIn7yom7eDI1ayhrvtQ28ebZPDwmBj6Y0MuyXA+AJ23aVc0oM7XEvszgwu4vKUSKCVDr843oMugeN0YA/RYKGW6M4ou5vNkv5m48eSdvfyafOsm2Z5XrHGWtaghusOM6OVesxDzoF4QsmHfTyDcfcOERSZxYgdMk89mv0UDUv41+47NXA7bYUOaqJZKL7ujZd0von5y3XJGImpQ7nLoCfq1YXUFukJqpSGss9RIAcg2WQrrwvFOnN/agPSaVaP7yvvIti13UqZ7ICZJ3TLihUf4tVApGd1aExgIr94E1mXcdrIAIChX2UGev83HpehBJioXZofIWqznQ3rpfn1WhM3oqC9hFS3XVLir3VOlSuHRgQUGUWTAAGEDCs6wBW+LLGZp2f0CMttyzgNKLhaLPlTOGt2zWR04azTxdkmCaWxwQSW44kut4gAY9qB7wPJGfxODuN7/CyE3zi4fff0uwhTFMmobBEQkjzwnjzCpdRfjCUTxsZiebrso/UK5r2LLsGQYzWdrgr8IO06xmb5H53aHjmXCNs=
    -
      # LTD_AWS_SECRET
      secure: vsZ4uvvU7REOjB97oGTmNtfD0ud55B5E2vd8uKimLJ7UHrhdYU6el/sxVggf4/LZgDoRpR1HvzVAsYk+web7HYRetwKzcbGemqYuGTZ+RePiwikByeQY0wPsQrlzKJ9WAEloLyffCMDb4kc9xhp5YpY/rwY8w0G0f7oKg3MQwCt6XyALPO0RC/Pe1wUgB7saHJkzG59cIaGQ7q+fLLUrAU0a294yxQU2uJEpnNtaCf8oS+C43O9H3VgCvJ8GeaTnGsQ8zvNbzb0lQjwUexVyVQdNyYu9GExqHFloCFa5MZn1u1AdwTENiXTuwP/3nO5f4uC8KF+1Y6e5OjdgnrzAQhopTa2yy8EjCih70oue+XqVIqYOz+QNt3LMtgpfw4sr3qSJL8weOYVJKe7Ap6wAxcsDJengUQkqN3SjRo4JEriDVNHEGceYM0KoiJz8F1ghx3bawVDn016AOdn66IHNv2qhKbV9WL11B7RqRxfehhUQPB38gZ7pUwyDwkRiOuh7KJ6aHWYTxlrE8oiOo/c2/Yf33RMq1iDKvQBpoM42On8FpwkcbQsUCLNVS8C+1R2neC8gS/oJ2MlK/mabBRhc8WMcKYy3LzMKwL+2Wl33RsSQmvEmaoQS22wIc6KT8PYf7MF3k4CkoEYzDcEXSWK8u0+LIt/D5jN0nBlYKlPZG+s=
    -
      # LTD_USERNAME
      secure: k5clHeZt+UzCdBSB10jT5iYyTk5GJF9k5fdu1G+bIVQH5CTae2NnU/6YIeJOMnLdAh4mw1P6NxCTbjofxtfOXGJOSofaTPBG1yQQQJSVaNxs7ZfW18wZO9L+j/lYApXf4ndiaxl4lDGy555KySIMcAji3gxAJiny83AeSz4g/DDLDlhRAnsS41X5/7/vS841G6ggeIMg+OUTJZIUpEkX4pI9rY1myY8cGP6bsPqrDKb4XZUOZgNs3X41RSP9lXm0zw7n/Ea0w3twjKIQbZC2jBD/26js1mxbr5Xs8hg6Kf6PUUZ5PcWxNXVkduG34l48ATW+szJhIuQ4DyjRqW5Cjwic9nydpjX47a5R1pJdegl3a4DM93BJr14kI2qYO0MtaHwvgaNeKCJeBTf4s9nx5npyK3o5BfT+XNAiSSJyVM7y4e1QLuJEXHv/wMoDC/3Xb7G4lsDtRUyyAPIgg9VWDTQRri275rug6AlUKpuPeih3y5ItcikOwVyL07QNTorvvDQWFjgBkauqQl6ykzmPKlGgHEfcP2+fkq/SP20tEwHMvQ7zsE9OBkZGuSd6f6L+rgTp+xrosFsWpOR4ZaQRVVnsEo9Y30CbBA6fWKYZuo2dFt3rHn+QpcfgGyvjcd4ao+i2ZFb6UMDW5NfHNU/3WC+9Pz/rsiBWksfxBU99uJE=
    -
      # LTD_PASSWORD
      secure: IABWAqi1cpIe3MVPMUvNT6ykV+ynTJ6Wphxy9S+Cm00eSboGszQTyKJEtlxKwZY++o4IA15x7tG8i1o7vajk5O8kPXTZbbH8thqvil312//XqbESG9aGksUgOMknoRF/7f+FbSfmRBjh6vvLuP2zL1+8VoFQeXHhIvLNSyeQsJKoiamLucCSJj6YzxJnwGqlYBPPdjMSQWdHG7ayVMidnksm3bSi9Rl8t4nqgSIidavXfgmaB/olHFD6zlxSdPR38OGJJUNBrGglaDHEUIaafwsDwPG6kIYXvhx5mURJuBZn5gQG3S4YHcvQZrzTx/7j6mZoXsik6Qu93PEzrw/ZJxDdV8e+SUKOndW8IIY3c/gVJgIa8wegQILgR+iYeRuOV9wZ1cNpOlAFNWEKIACWXj2sTzAaRfy99qtLrf39bn73fPnooHyGWSiFwhropxPKxYd54nhkE+aDbJ+KaxMMGfPrtZNMRoMSHv3vSC2yWx41MZ5+W+1GyzGoAOxhp8qqe3MUQKFiIutod6DrJzuPR8XFJc1ZUCel4XvS1H5udCBxRtMNcVo8i95VrSalVElJmg4lIpCslF2fjqSekz+d6vKxuszcJZ0Jdb35Wpayok/DKk9hsp12SAGThSJb9B0dRlm2fGXM2/2ZHmSCA2rSrczJO2HbnQvf1qIc7y7z+4s=
